apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: str-rolebinding
  namespace: default
subjects:
- kind: User
  name: str # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: str-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io