apiVersion: v1
kind: Service
metadata:
  name: deploy-svc
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: network-multitool-http
    port: 1180
    protocol: TCP
    targetPort: 1180
  - name: network-multitool-https
    port: 11443
    protocol: TCP
    targetPort: 11443
  selector:
    app: nginx
