apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-dep
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        volumeMounts:
        - name: pvc
          mountPath: /nfs-test
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: nfs-pvc