apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', "while true; do echo sometext >> /pvcOutput/file.txt;sleep 5; done"]
        volumeMounts:
        - name: pvc
          mountPath: /pvcOutput
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        volumeMounts:
        - name: pvc
          mountPath: /input
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: local-pvc